#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# checkmk_dell_rackpdu - Checkmk extension for Dell Rack PDUs
#
# Copyright (C) 2021  Marius Rieder <marius.rieder@scs.ch>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# .1.3.6.1.4.1.674.10903.200.2.200.130.2.2.1.3.1 Outlet 1 --> DellrPDU-MIB::rPDUOutletMeteredStatusName.1
# .1.3.6.1.4.1.674.10903.200.2.200.130.2.2.1.3.2 Outlet 2 --> DellrPDU-MIB::rPDUOutletMeteredStatusName.2
# .1.3.6.1.4.1.674.10903.200.2.200.130.2.2.1.5.1 2750 --> DellrPDU-MIB::rPDUOutMeteredStatPowerRating.1
# .1.3.6.1.4.1.674.10903.200.2.200.130.2.2.1.5.2 2750 --> DellrPDU-MIB::rPDUOutMeteredStatPowerRating.2
# .1.3.6.1.4.1.674.10903.200.2.200.130.2.2.1.8.1 0 --> DellrPDU-MIB::rPDUOutletMeteredStatusPower.1
# .1.3.6.1.4.1.674.10903.200.2.200.130.2.2.1.8.2 0 --> DellrPDU-MIB::rPDUOutletMeteredStatusPower.2
# .1.3.6.1.4.1.674.10903.200.2.200.130.2.2.1.11.1 2 --> DellrPDU-MIB::rPDUOutMeteredStatusLoadState.1
# .1.3.6.1.4.1.674.10903.200.2.200.130.2.2.1.11.2 2 --> DellrPDU-MIB::rPDUOutMeteredStatusLoadState.2
# .1.3.6.1.4.1.674.10903.200.2.200.130.2.4.1.5.1 2000 --> DellrPDU-MIB::rPDUOutMtrdCfgNrOvdCurntThresh.1
# .1.3.6.1.4.1.674.10903.200.2.200.130.2.4.1.5.2 2000 --> DellrPDU-MIB::rPDUOutMtrdCfgNrOvdCurntThresh.2
# .1.3.6.1.4.1.674.10903.200.2.200.130.2.4.1.6.1 2500 --> DellrPDU-MIB::rPDUOutMtredCfgOvrldCurntThresh.1
# .1.3.6.1.4.1.674.10903.200.2.200.130.2.4.1.6.2 2500 --> DellrPDU-MIB::rPDUOutMtredCfgOvrldCurntThresh.2

from cmk.base.check_legacy_includes.elphase import *  # pylint: disable=wildcard-import,unused-wildcard-import


def parse_dell_rackpdu_powerswitch(info):
    def get_status_info(power_str, device_state):
        return float(power_str), {
            '1': (2, 'load low'),
            '2': (0, 'load normal'),
            '3': (1, 'load near over load'),
            '4': (2, 'load over load'),
        }[device_state]

    parsed = {}
    outlet_infos, outlet_configs = info

    for idx, outlet_info in enumerate(outlet_infos):
        outlet_config = outlet_configs[idx]

        outlet_name, power_str, power_max_str, device_state = outlet_info
        warn, crit = outlet_configs[idx]

        parsed[outlet_name] = {
            'power': get_status_info(power_str, device_state),
            'params': {
                'power': (saveint(warn), saveint(crit))
            }
        }

    return parsed


def check_dell_rackpdu_powerswitch(item, cmkparams, parsed):
    params = parsed[item]['params']
    params.update(cmkparams)
    return check_elphase(item, params, parsed)


check_info['dell_rackpdu_powerswitch'] = {
    'parse_function'        : parse_dell_rackpdu_powerswitch,
    'inventory_function'    : inventory_elphase,
    'check_function'        : check_dell_rackpdu_powerswitch,
    'service_description'   : 'Power Outlet Port %s',
    'has_perfdata'          : True,
    'snmp_info'             : [('.1.3.6.1.4.1.674.10903.200.2.200.130.2.2.1', [
                                    '3',    # DellrPDU-MIB::rPDUOutletMeteredStatusName
                                    '8',    # DellrPDU-MIB::rPDUOutletMeteredStatusPower
                                    '5',    # DellrPDU-MIB::rPDUOutletMeteredStatusPowerRating
                                    '11',   # DellrPDU-MIB::rPDUOutletMeteredStatusLoadState
                               ]),
                               ('.1.3.6.1.4.1.674.10903.200.2.200.130.2.4.1', [
                                    '5',    # DellrPDU-MIB::rPDUOutletMtrdCfgNrOvdCurntThresh
                                    '6',    # DellrPDU-MIB::rPDUOutletMtredCfgOvrldCurntThresh
                              ])],
    'snmp_scan_function'    : lambda oid: oid('.1.3.6.1.2.1.1.1.0').lower().startswith('dell web/snmp')\
                                          and oid('.1.3.6.1.4.1.674.10903.200.2.200.130.2.*'),
    'group'                 : 'ups_outphase',
}
